export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import RootLayout from "../[lang]/layout";

export default function RootLayoutWrapper(props: {
  children: React.ReactNode;
}) {
  return <RootLayout children={props.children} params={Promise.resolve({ lang: "no" })} />;
}
